//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PAIS
    {
        public TBL_PAIS()
        {
            this.TBL_FABRICANTES = new HashSet<TBL_FABRICANTES>();
        }
    
        public int C_ID_PAIS { get; set; }
        public string C_NOMBRE_PAIS { get; set; }
    
        public virtual ICollection<TBL_FABRICANTES> TBL_FABRICANTES { get; set; }
    }
}
