//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SERVICIOS
    {
        public TBL_SERVICIOS()
        {
            this.TBL_DETALLE_ENCABEZADO_FACTURA = new HashSet<TBL_DETALLE_ENCABEZADO_FACTURA>();
        }
    
        public int C_ID_SERVICIO { get; set; }
        public string C_NOMBRE_SERVICIO { get; set; }
        public decimal C_PRECIO { get; set; }
    
        public virtual ICollection<TBL_DETALLE_ENCABEZADO_FACTURA> TBL_DETALLE_ENCABEZADO_FACTURA { get; set; }
    }
}
