//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DETALLE_ENCABEZADO_FACTURA
    {
        public int C_ID_DETALLE { get; set; }
        public int C_FK_ENCABEZAFO_FACTURA { get; set; }
        public int C_FK_SERVICIO { get; set; }
        public int C_CANTIDAD { get; set; }
        public decimal C_PRECIO { get; set; }
        public decimal C_SUBTOTAL { get; set; }
    
        public virtual TBL_ENCABEZADO_FACTURA TBL_ENCABEZADO_FACTURA { get; set; }
        public virtual TBL_SERVICIOS TBL_SERVICIOS { get; set; }
    }
}
