//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_VEHICULO
    {
        public TBL_VEHICULO()
        {
            this.TBL_ENCABEZADO_FACTURA = new HashSet<TBL_ENCABEZADO_FACTURA>();
            this.TBL_VEHICULO_CLIENTE = new HashSet<TBL_VEHICULO_CLIENTE>();
        }
    
        public int C_ID_VEHICULO { get; set; }
        public string C_PLACA { get; set; }
        public int C_FK_MARCA { get; set; }
        public int C_FK_TIPO { get; set; }
        public int C_FK_MODELO { get; set; }
        public short C_CANT_PUERTAS { get; set; }
        public short C_CANT_RUEDAS { get; set; }
        public string C_YEAR { get; set; }
    
        public virtual ICollection<TBL_ENCABEZADO_FACTURA> TBL_ENCABEZADO_FACTURA { get; set; }
        public virtual TBL_MARCA TBL_MARCA { get; set; }
        public virtual TBL_MODELO TBL_MODELO { get; set; }
        public virtual TBL_TIPO_VEHICULO TBL_TIPO_VEHICULO { get; set; }
        public virtual ICollection<TBL_VEHICULO_CLIENTE> TBL_VEHICULO_CLIENTE { get; set; }
    }
}
