//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MODELO
    {
        public TBL_MODELO()
        {
            this.TBL_VEHICULO = new HashSet<TBL_VEHICULO>();
        }
    
        public int C_ID_MODELO { get; set; }
        public string C_NOMBRE_MODELO { get; set; }
        public Nullable<int> C_FK_MARCA { get; set; }
    
        public virtual TBL_MARCA TBL_MARCA { get; set; }
        public virtual ICollection<TBL_VEHICULO> TBL_VEHICULO { get; set; }
    }
}
