//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TIPO_MOVIMIENTO_CAJA
    {
        public TBL_TIPO_MOVIMIENTO_CAJA()
        {
            this.TBL_APERTURA_CIERRE_CAJA = new HashSet<TBL_APERTURA_CIERRE_CAJA>();
        }
    
        public int C_ID_MOVIMIENTO { get; set; }
        public string C_NOMBRE_TIPO { get; set; }
    
        public virtual ICollection<TBL_APERTURA_CIERRE_CAJA> TBL_APERTURA_CIERRE_CAJA { get; set; }
    }
}
