//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_APERTURA_CIERRE_CAJA
    {
        public int C_ID_APERTURA { get; set; }
        public System.DateTime C_FECHA_MOVIMIENTO { get; set; }
        public int C_FK_TIPO_MOVIMIENTO { get; set; }
        public int C_FK_USUARIO { get; set; }
    
        public virtual TBL_TIPO_MOVIMIENTO_CAJA TBL_TIPO_MOVIMIENTO_CAJA { get; set; }
        public virtual TBL_USUARIOS TBL_USUARIOS { get; set; }
    }
}
