//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ENCABEZADO_FACTURA
    {
        public TBL_ENCABEZADO_FACTURA()
        {
            this.TBL_DETALLE_ENCABEZADO_FACTURA = new HashSet<TBL_DETALLE_ENCABEZADO_FACTURA>();
        }
    
        public int C_ID_ENCABEZADO_FACTURA { get; set; }
        public int C_FK_CLIENTE { get; set; }
        public int C_FK_VEHICULO { get; set; }
        public System.DateTime C_FECHA { get; set; }
        public decimal C_SUBTOTAL { get; set; }
        public decimal C_TOTAL { get; set; }
        public decimal C_TOTAL_IMPUESTO { get; set; }
        public bool C_ESTADO { get; set; }
    
        public virtual TBL_CLIENTE TBL_CLIENTE { get; set; }
        public virtual ICollection<TBL_DETALLE_ENCABEZADO_FACTURA> TBL_DETALLE_ENCABEZADO_FACTURA { get; set; }
        public virtual TBL_VEHICULO TBL_VEHICULO { get; set; }
    }
}
