//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INGRESOS_USUARIOS
    {
        public int C_ID_INGRESOS { get; set; }
        public System.DateTime C_INGRESO { get; set; }
        public int C_FK_USUARIO { get; set; }
    
        public virtual TBL_USUARIOS TBL_USUARIOS { get; set; }
    }
}
