//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MARCA
    {
        public TBL_MARCA()
        {
            this.TBL_MODELO = new HashSet<TBL_MODELO>();
            this.TBL_VEHICULO = new HashSet<TBL_VEHICULO>();
        }
    
        public int C_ID_MARCA { get; set; }
        public string C_NOMBRE_MARCA { get; set; }
        public Nullable<int> C_FK_FABRICANTE { get; set; }
    
        public virtual TBL_FABRICANTES TBL_FABRICANTES { get; set; }
        public virtual ICollection<TBL_MODELO> TBL_MODELO { get; set; }
        public virtual ICollection<TBL_VEHICULO> TBL_VEHICULO { get; set; }
    }
}
