//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FABRICANTES
    {
        public TBL_FABRICANTES()
        {
            this.TBL_MARCA = new HashSet<TBL_MARCA>();
        }
    
        public int C_ID_FABRICANTE { get; set; }
        public string C_NOMBRE_FABRICANTE { get; set; }
        public Nullable<int> C_FK_PAIS { get; set; }
    
        public virtual TBL_PAIS TBL_PAIS { get; set; }
        public virtual ICollection<TBL_MARCA> TBL_MARCA { get; set; }
    }
}
