//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PARAMETROS
    {
        public int C_ID_PARAMETROS { get; set; }
        public string C_NOMBRE_ORGANIZACION { get; set; }
        public string C_CORREO_APERTURA { get; set; }
        public string C_CORREO_CIERRE { get; set; }
        public decimal C_MONTO_MINIMO { get; set; }
    }
}
