//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TIPO_VEHICULO
    {
        public TBL_TIPO_VEHICULO()
        {
            this.TBL_VEHICULO = new HashSet<TBL_VEHICULO>();
        }
    
        public int C_ID_TIPO_VEHICULO { get; set; }
        public string C_NOMBRE_TIPO { get; set; }
    
        public virtual ICollection<TBL_VEHICULO> TBL_VEHICULO { get; set; }
    }
}
